"""empty message

Revision ID: 037a62ccc366
Revises: 
Create Date: 2024-05-08 23:36:05.481315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037a62ccc366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('montant_paye', sa.Float(), nullable=False),
    sa.Column('montant_rendu', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('details_facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('coiffure_id', sa.Integer(), nullable=True),
    sa.Column('quantite_produit', sa.Integer(), nullable=True),
    sa.Column('quantite_coiffure', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coiffure_id'], ['coiffure.id'], ),
    sa.ForeignKeyConstraint(['facture_id'], ['facture.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details_facture')
    op.drop_table('facture')
    # ### end Alembic commands ###
