"""empty message

Revision ID: 0e8ac0b3db5d
Revises: 553eda3e166f
Create Date: 2024-04-14 23:46:04.171191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8ac0b3db5d'
down_revision = '553eda3e166f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_abonnement', schema=None) as batch_op:
        batch_op.drop_column('montant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_abonnement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('montant', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
