"""empty message

Revision ID: 553eda3e166f
Revises: 
Create Date: 2024-04-14 22:29:36.700855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553eda3e166f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
