"""empty message

Revision ID: 87a7844a0833
Revises: 72d5368f5c88
Create Date: 2024-04-27 22:23:33.938989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a7844a0833'
down_revision = '72d5368f5c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.alter_column('produit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('coiffure_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.alter_column('coiffure_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('produit_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
