"""empty message

Revision ID: b30ca376648b
Revises: 
Create Date: 2024-04-18 22:18:37.014493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30ca376648b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('prenom', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('telephone', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('adresse', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('adresse')
        batch_op.drop_column('telephone')
        batch_op.drop_column('prenom')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
