"""empty message

Revision ID: e6ff4cdb6c37
Revises: 87a7844a0833
Create Date: 2024-04-27 22:50:35.321368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ff4cdb6c37'
down_revision = '87a7844a0833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite_coiffure', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantite_produit', sa.Integer(), nullable=True))
        batch_op.drop_column('quantite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite', sa.INTEGER(), nullable=False))
        batch_op.drop_column('quantite_produit')
        batch_op.drop_column('quantite_coiffure')

    # ### end Alembic commands ###
