"""empty message

Revision ID: f3cbb33c23b0
Revises: 059882f6d9ac
Create Date: 2024-05-06 11:17:01.748722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cbb33c23b0'
down_revision = '059882f6d9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caisse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caisse')
    # ### end Alembic commands ###
